### ISSUE TITLE
wrap_detect_q is never set on for one-shot sniffing

### ISSUE THREAD

**Issue by vvavrychuk** [ultraembedded/cores#3]
For `wrap_detect_q` to be one we need `buffer_wr_q` on when `write_addr_q == buffer_end_w`. But since  `write_addr_q == buffer_end_w` we get `buffer_full_w` and it moves us to `STATE_RX_DATA_IGNORE` and we will never get `write_addr_q`.

**Comment by ultraembedded** [comment]
I've replaced the usb_sniffer core with a completely new implementation. I think this issue no longer applies.
