### ISSUE TITLE
Sdram_axi ip

### ISSUE THREAD

**Issue by ishitashah7** [ultraembedded/cores#5]
Hi,
I want to know if the sdram_axi controller IP verified and tested ?
Can I get a document specifying each detail of it

**Comment by ultraembedded** [comment]
The SDRAM_AXI component is well exercised, both in simulation (constrained random testing) against a couple manufacturer models, and on a number of FPGA projects.
I haven't seen any issues.

The only configuration you need to get right is the params which match your SDRAM;
- SDRAM_MHZ
- SDRAM_ADDR_W
- SDRAM_COL_W
- SDRAM_READ_LATENCY

These are all documented in README for the core;
https://github.com/ultraembedded/core_sdram_axi4
